// List of districts
const districts = [
  "AAAAAAMBALA",
  "Anti Corruption Bureau, Haryana",
  "BHIWANI",
  "CHARKHI DADRI",
  "DABWALI",
  "FARIDABAD",
  "FATEHABAD",
  "GRP AMBALA CANTT",
  "GURUGRAM",
  "HANSI",
  "Haryana State Enforcement Bureau (HSEnB)",
  "HARYANA STATE NARCOTICS CONTROL BUREAU,MADHUBAN KARNAL",
  "HISAR",
  "JHAJJAR",
  "JIND",
  "KAITHAL",
  "KARNAL",
  "KURUKSHETRA",
  "MAHENDERGARH",
  "NUH",
  "PALWAL",
  "PANCHKULA",
  "PANIPAT",
  "REWARI",
  "ROHTAK",
  "SIRSA",
  "SONIPAT",
  "State Crime Branch",
  "YAMUNA NAGAR"
];
  
  // Mapping of districts to police stations
  const haryana_police_stations = {'AMBALA': [
    'AMBALA CANTT',
    'AMBALA CITY',
    'AMBALA SADAR',
    'BALDEV NAGAR',
    'BARARA',
    'MAHESH NAGAR',
    'MULLANA',
    'NAGGAL',
    'NARAINGARH',
    'PANJOKHRA',
    'PARAO AMBALA CANTT',
    'PS CYBER CRIME AMBALA',
    'SAHA',
    'SECTOR-9, AMBALA CITY',
    'SHAHZADPUR',
    'TRAFFIC',
    'WOMEN POLICE STATION NARAINGARH, AMBALA',
    'WOMEN POLICE STATION, AMBALA'],
   'Anti Corruption Bureau, Haryana': [
    'ACB, Ambala',
    'ACB, Faridabad',
    'ACB, Gurugram',
    'ACB, Hisar',
    'ACB, Karnal',
    'ACB, Panchkula',
    'ACB, Rohtak'],
   'BHIWANI': [
    'BAWANI KHERA',
    'BEHAL',
    'BHIWANI CITY',
    'BHIWANI CIVIL LINES',
    'BHIWANI SADAR',
    'BOND KALAN',
    'Cyber Crime Police Station, Bhiwani',
    'DADRI CITY',
    'DADRI SADAR',
    'JUI KALAN PS BHIWANI',
    'LOHARU',
    'PS INDUSTRIAL AREA, BHIWANI',
    'SIWANI',
    'TOSHAM',
    'TRAFFIC',
    'WOMEN POLICE STATION, BHIWANI'],
   'CHARKHI DADRI': [
    'BADHRA',
    'BOND KALAN',
    'DADRI CITY',
    'DADRI SADAR',
    'JHOJHU KALAN',
    'PS Cyber Crime, Charkhi Dadri',
    'Women Police Station, Charkhi Dadri'],
   'DABWALI': [
    'BARAGUDHA',
    'CITY MANDI DABWALI',
    'DABWALI SADAR',
    'KALAN WALI',
    'ODHAN',
    'RORI',
    'Women Police Station Dabwali,Sirsa'],
   'FARIDABAD': [
    'ADARSH NAGAR',
    'BALLABHGARH CITY',
    'BALLABHGARH SADAR',
    'BHUPANI',
    'CHHANSA',
    'DABUA',
    'DHAUJ',
    'FARIDABAD CENTRAL',
    'FARIDABAD KOTWALI',
    'FARIDABAD N.I.T.',
    'FARIDABAD OLD',
    'KHERIPUL',
    'Metro Police Station Faridabad',
    'MUJESAR',
    'PALLA',
    'Polilce Station B.P.T.P.',
    'PS Cyber Crime Ballabgarh',
    'PS Cyber Crime Central',
    'PS Cyber Crime NIT',
    'S.G.M. NAGAR (SANJAY GANDHI MEMORIAL NAGAR)',
    'SARAI KHAWAJA',
    'SARAN',
    'SECTOR - 8',
    'SECTOR-17',
    'SECTOR-31 FARIDABAD',
    'SECTOR-58',
    'SURAJ KUND',
    'TIGAON',
    'TRAFFIC',
    'Women Police Station Ballabgarh',
    'Women Police Station NIT,Faridabad',
    'WOMEN POLICE STATION, FARIDABAD'],
   'FATEHABAD': [
    'BHATTU KALAN',
    'BHUNA',
    'CITY FATEHABAD',
    'CITY RATIA',
    'CITY TOHANA',
    'Cyber Crime Police Station Fatehabad',
    'JAKHAL',
    'SADAR FATEHABAD',
    'SADAR RATTIA',
    'SADAR TOHANA',
    'TRAFFIC',
    'WOMEN POLICE STATION, FATEHABAD'],
   'GRP AMBALA CANTT': [
    'GRP AMBALA Cantt',
    'GRP BAHADURGARH',
    'GRP CHANDIGARH',
    'GRP FARIDABAD',
    'GRP GURUGRAM',
    'GRP HISAR',
    'GRP JAGADHARI',
    'GRP JIND',
    'GRP KALKA',
    'GRP KARNAL',
    'GRP KURUKSHETRA',
    'GRP PANIPAT',
    'GRP REWARI',
    'GRP ROHTAK',
    'GRP SIRSA',
    'GRP SONIPAT'],
   'GURUGRAM': [
    'BADSHAHPUR',
    'BAJGHERA',
    'BHONDSI',
    'BILASPUR GURUGRAM',
    'CITY SOHANA',
    'CIVIL LINES GURGAON',
    'Cyber Crime Police Station, Gurugram',
    'DLF',
    'DLF PH-3rd',
    'DLF PHASE-1',
    'DLF-II',
    'FURRUKH NAGAR',
    'GURGAON CITY',
    'GURGAON SADAR',
    'INDUSTRIAL SECTOR - 7, MANESAR',
    'KHEDKI DAULA',
    'MANESAR',
    'METRO',
    'NEW COLONY',
    'PALAM VIHAR',
    'PATAUDI',
    'PS Cyber Manesar',
    'PS Cyber South',
    'PS Cyber West',
    'RAJENDRA PARK',
    'SECTOR - 37',
    'SECTOR - 50',
    'SECTOR - 53',
    'SECTOR - 9A',
    'SECTOR-10',
    'SECTOR-14, Gurugram',
    'SECTOR-17 / 18',
    'SECTOR-40',
    'SECTOR-5, GURGAON',
    'SECTOR-56',
    'SECTOR-65',
    'SHIVAJI NAGAR',
    'SOHNA',
    'SUSHANT LOK',
    'TRAFFIC - I',
    'TRAFFIC - II',
    'TRAFFIC PS KMP, GURUGRAM',
    'UDYOG VIHAR',
    'WOMEN POLICE STATION MANESAR,GURUGRAM',
    'WOMEN POLICE STATION, GURGAON',
    'Women West Gurugram'],
   'HANSI': [
    'BASS',
    'HANSI CITY',
    'HANSI SADAR',
    'NARNAUND',
    'PS CYBER CRIME, HANSI',
    'PS Traffic Hansi',
    'Women Police Station, HANSI'],
   'Haryana State Enforcement Bureau (HSEnB)': [
    'HSEnB Police Station Ambala',
    'HSEnB Police Station Faridabad',
    'HSEnB Police Station Gurugram',
    'HSEnB Police Station Hisar',
    'HSEnB Police Station Jind',
    'HSEnB Police Station Karnal',
    'HSEnB Police Station Rewari',
    'HSEnB Police Station Rohtk'],
   'HARYANA STATE NARCOTICS CONTROL BUREAU,MADHUBAN KARNAL': [
    'HSNCB Unit Ambala',
    'HSNCB Unit Bhiwani',
    'HSNCB Unit Faridabad ',
    'HSNCB Unit Fatehabad',
    'HSNCB Unit Gurugram',
    'HSNCB Unit Hisar',
    'HSNCB Unit Karnal',
    'HSNCB Unit Kurukshetra',
    'HSNCB Unit Rewari',
    'HSNCB Unit Rohtak',
    'HSNCB Unit Sirsa'],
   'HISAR': [
    'ADAMPUR',
    'AGROHA',
    'AZAD NAGAR HISAR',
    'BARWALA',
    'Cyber Crime, Police Station Hisar',
    'HISAR CITY',
    'HISAR CIVIL LINES',
    'HISAR SADAR',
    'HTM HISAR',
    'TRAFFIC',
    'UKLANA',
    'URBAN ESTATE HISAR',
    'WOMEN POLICE STATION, HISSAR'],
   'JHAJJAR': [
    'ASAUDA',
    'BADLI',
    'BERI',
    'CITY BAHADURGARH',
    'CITY JHAJJAR',
    'DUJANA',
    'LINE PAR BAHADURGARH',
    'MACHHROLI',
    'PS Cyber Jhajjar',
    'SADAR BAHADURGARH',
    'SADAR JHAJJAR',
    'SAHLAWAS',
    'SECTOR-06 BAHADURGRH',
    'TRAFFIC BAHADURGARH',
    'WOMEN POLICE STATION, JHAJJAR',
    'WOMEN PS BAHADURGARH,JHAJJAR'],
   'JIND': [
    'ALEWA',
    'CITY SAFIDON',
    'Civil line Jind',
    'GARHI',
    'JIND CITY',
    'JIND SADAR',
    'JULANA',
    'NARWANA CITY',
    'NARWANA SADAR',
    'PILLU KHERA',
    'PS Cyber, District Jind',
    'SAFIDON',
    'TRAFFIC',
    'UCHANA',
    'WOMEN POLICE STATION, JIND'],
   'KAITHAL': [
    '\xa0Cyber Crime Police Station Kaithal',
    'CHEEKA',
    'CIVIL LINE KAITHAL',
    'Dhand',
    'GUHLA',
    'KAITHAL CITY',
    'KAITHAL SADAR',
    'KALAYAT',
    'PUNDRI',
    'RAJAUND',
    'SIWAN',
    'TITRAM',
    'TRAFFIC',
    'WOMEN POLICE STATION, KAITHAL'],
   'KARNAL': [
    'ASSANDH',
    'BUTANA',
    'Cyber Crime police station karnal',
    'GHARAUNDA',
    'INDRI',
    'KARNAL CITY',
    'KARNAL CIVIL LINES',
    'KARNAL SADAR',
    'KUNJPURA',
    'MADHUBAN',
    'MUNAK, KARNAL',
    'NIGDHU KARNAL',
    'NISSING',
    'RAM NAGAR KARNAL',
    'SECTOR 32-33 KARNAL',
    'TARAORI',
    'TRAFFIC',
    'Women Police Station Assand,Karnal',
    'WOMEN POLICE STATION, KARNAL'],
   'KURUKSHETRA': [
    'BABAIN',
    'CITY PEHOWA, KURUKSHETRA',
    'CYBER CRIME POLICE STATION, KURUKSHETRA',
    'ISMAILABAD',
    'JHANSA',
    'KRISHANA GATE, THANASAR KURUKSHETRA',
    'KURUKSHETRA UNIVERSITY',
    'LADWA',
    'PEHOWA',
    'SHAHABAD',
    'THANESAR CITY',
    'THANESAR SADAR',
    'TRAFFIC',
    'WOMEN POLICE STATION, KURUKSHETRA'],
   'MAHENDERGARH': [
    'ATELI',
    'CITY KANINA',
    'CITY MAHENDERGARH',
    'CITY NARNAUL',
    'CYBER POLICE STATION, MAHENDERGARH',
    'NANGAL CHAUDHRI',
    'NIZAMPUR',
    'SADAR KANINA',
    'SADAR MAHENDERGARH',
    'SADAR NARNAUL',
    'SATNALI',
    'TRAFFIC',
    'WOMEN POLICE STATION, NARNAUL'],
   'NUH': [
    'BICCHOR',
    'CITY NUH',
    'CITY TAURU',
    'FEROZEPUR JHIRKA',
    'NAGINA',
    'PINANGWA',
    'PS Akera',
    'PS City Firozpur Jhirka',
    'PS City Punhana',
    'PS Cyber Crime Nuh(Mewat)',
    'PS Mohammadpur Ahir',
    'PS Traffic (KMP) Dhulawat ',
    'PUNHANA',
    'ROZKA MEO',
    'SADAR NUH',
    'SADAR TAURU',
    'TRAFFIC',
    'WOMEN POLICE STATION, MEWAT'],
   'PALWAL': [
    'BAHIN',
    'CAMP PALWAL',
    'CHAND HUT',
    'CITY PALWAL',
    'GADPURI',
    'HASSANPUR',
    'HATHIN',
    'HODAL',
    'MUNDKATI',
    'PS Cyber Crime, District Palwal',
    'SADAR PALWAL',
    'TRAFFIC',
    'UTAWAR',
    'WOMEN POLICE STATION, PALWAL'],
   'PANCHKULA': [
    'CHANDIMANDIR',
    'CYBER CRIME',
    'KALKA',
    'MANSA DEVI COMPLEX',
    'PANCHKULA SECTOR-5',
    'PINJORE',
    'RAIPUR RANI',
    'SECTOR-14, PANCHKULA',
    'SECTOR-20',
    'SECTOR-7, PANCHKULA',
    'TRAFFIC',
    'WOMEN POLICE STATION, PANCHKULA'],
   'PANIPAT': [
    'BAPOLI',
    'CHANDNIBAGH',
    'Cyber Crime Police Station Panipat',
    'Industrial Sector 29 Panipat',
    'ISRANA',
    'MATLAUDA',
    'Model Town Panipat',
    'Old Industrial Panipat',
    'PANIPAT CITY',
    'PANIPAT SADAR',
    'Quilla Panipat',
    'SAMALKHA',
    'SANOLI',
    'SECTOR 13/17 PANIPAT',
    'Tehsil Camp Panipat',
    'TRAFFIC',
    'WOMEN POLICE STATION, PANIPAT'],
   'REWARI': [
    'BAWAL',
    'CIA KOSLI',
    'DHARUHERA',
    'JATUSANA',
    'KASOLA',
    'KHOL',
    'KOSLI',
    'MODEL TOWN REWARI',
    'POLICE STATION CYBER CRIME, REWARI',
    'RAMPURA',
    'REWARI CITY',
    'REWARI SADAR',
    'ROHADAI',
    'SEC-6, DHARUHERA',
    'TRAFFIC',
    'WOMEN POLICE STATION, REWARI'],
   'ROHTAK': [
    'ARYA NAGAR ROHTAK',
    'BAHUAKBARPUR',
    'Cyber Police Station Rohtak',
    'I.M.T. ROHTAK',
    'KALANAUR',
    'LAKHAN MAJRA',
    'MEHAM',
    'P.G.I.M.S. ROHTAK',
    'PURANI SABZI MANDI ROHTAK',
    'ROHTAK CITY',
    'ROHTAK CIVIL LINES',
    'ROHTAK SADAR',
    'SAMPLA',
    'SHIVAJI COLONY',
    'TRAFFIC',
    'URBAN ESTATE ROHTAK',
    'WOMEN POLICE STATION, ROHTAK'],
   'SIRSA': [
    'BARAGUDHA(Sirsa)',
    'CITY MANDI DABWALI(Sirsa)',
    'Cyber Crime Police Station Sirsa',
    'DABWALI SADAR(Sirsa)',
    'DING',
    'ELLENABAD',
    'KALAN WALI(Sirsa)',
    'NATHU SARAI CHOPTA',
    'ODHAN(Sirsa)',
    'Police Station,Civil Line Sirsa',
    'RANIA',
    'RORI(Sirsa)',
    'SIRSA CITY',
    'SIRSA SADAR',
    'TRAFFIC',
    'Women Police Station Dabwali(Sirsa)',
    'WOMEN POLICE STATION, SIRSA'],
   'SONIPAT': [
    'BAHALGARH',
    'BARAUDA',
    'CIVIL LINE SONIPAT',
    'GANNAUR',
    'GOHANA CITY',
    'GOHANA SADAR',
    'HSIDC BARHI',
    'KHARKHODA',
    'KUNDLI',
    'MOOHANA',
    'MURTHAL',
    'PS Cyber Sonipat',
    'RAI',
    'SECTOR-27, SONIPAT',
    'SONIPAT CITY',
    'SONIPAT SADAR',
    'TRAFFIC',
    'TRAFFIC MURTHAL',
    'WOMEN POLICE STATION',
    'WOMEN PS GOHANA',
    'WOMEN PS KHANPUR KALAN'],
   'State Crime Branch': ['Nodal Cyber Crime Police Station, Haryana'],
   'YAMUNA NAGAR': ['BILASPUR',
    'BURIA',
    'CHHACHHRAULI',
    'CHHAPAR',
    'Cyber Crime Police Station, Yamunanagar',
    'FARAKPUR',
    'GANDHI NAGAR, YAMUNANAGAR',
    'JAGADDHRI SADAR',
    'JAGADHRI CITY',
    'JATHLANA',
    'PRATAP NAGAR',
    'RADAUR',
    'SADHAURA',
    'SEC.17 HUDA, JAGADHRI YAMUNANAGAR',
    'TRAFFIC',
    'WOMEN POLICE STATION, YAMUNA NAGAR',
    'YAMUNA NAGAR CITY',
    'YAMUNA NAGAR SADAR']};
  